# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/echoform/build_xcode/JUCE/tools/JUCEToolsExport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/CMake/JUCECheckAtomic.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/CMake/JUCEConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/CMake/JUCEHelperTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/CMake/JUCEModuleSupport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/CMake/JUCEUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/extras/Build/juceaide/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/juce/modules/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/BasicConfigVersion-ExactVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/noisebox/Documents/3_Development/Repos/echoform/build_xcode/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/noisebox/Documents/3_Development/Repos/echoform/build_xcode/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/opt/homebrew/bin/cmake -P /Users/noisebox/Documents/3_Development/Repos/echoform/build_xcode/CMakeFiles/VerifyGlobs.cmake

/Users/noisebox/Documents/3_Development/Repos/echoform/build_xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/noisebox/Documents/3_Development/Repos/echoform -B/Users/noisebox/Documents/3_Development/Repos/echoform/build_xcode
